version: "3"

services:

  postgres:
    container_name: db_jira
    image: postgres
    expose:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    networks:
      - jirarush-network
    restart: always

  app-server:
    container_name: server_jira
    build:
      context: .
      dockerfile: Dockerfile
    image: jira-app
    expose:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/jira
      DB_USERNAME: jira
      DB_PASSWORD: JiraRush
    depends_on:
      - postgres
    networks:
      - jirarush-network
    restart: always


  nginx:
    container_name: nginx_jira
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources/:/opt/jirarush/resources/
    depends_on:
      - app-server
    networks:
      - jirarush-network
    restart: always

networks:
  jirarush-network:
    driver: bridge